
name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build APK
        run: |
          BUILD_OUTPUT=$(eas build --platform android --profile production --non-interactive --json)
          echo "EAS Build Output:"
          echo $BUILD_OUTPUT
          APK_URL=$(echo $BUILD_OUTPUT | jq -r '.artifacts.buildUrl')
          echo "Found APK URL: $APK_URL"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
